### PR TITLE
You didn't have enough cinsts as I said :)

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Can you squash this down to a singular commit? Thanks!

**Comment by majkinetor** [comment]
I believe its easier for you to do that during merge ?

**Comment by majkinetor** [comment]
Created new PR for this.

**Comment by gep13** [comment]
>@majkinetor said...
Created new PR for this.

Just for your information, it shouldn't have been necessary to create a new PR.  The steps required to do what was being asked can be found here: https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request

**Comment by majkinetor** [comment]
I couldn't get rid of merge commit.

**Comment by ferventcoder** [comment]
It's almost never necessary to create a new PR - git is a very powerful platform. It actually takes more time to not rebase/squash, plus it reduces conversations/feedback/review in a single place.

For reference - a squash and push takes around 30 seconds.

**Comment by ferventcoder** [comment]
Ah, never use pull. Almost always you want fetch and rebase.

**Comment by ferventcoder** [comment]
Pull uses merge - merge should be intentional. Getting the latest changes and syncing your repo should never be a merge. Merge should only be used when you are merging two branches together, like stable -> master or merging a PR.

**Comment by majkinetor** [comment]
> Ah, never use pull. Almost always you want fetch and rebase.

Yeah, I got that after I did it... will have to unlearn pull, will probably take me some time.

Thanks for patience.

**Comment by ferventcoder** [comment]
It's a learning process. Git is one of those things you pick up new commands for over time. :)

**Pull request closed without merging**
