### PR TITLE
Added Hyper-V Provider section

### PR DESCRIPTION
**Pull request by gep13**
- To allow usage of Hyper-V box which has been pushed to here: https://app.vagrantup.com/ferventcoder/boxes/win2012r2-x64-nocm

### CODE REVIEW

**Comment by gep13** [comment]
@ferventcoder @mwrock what are your thoughts on this?

**Comment by gep13** [comment]
During the `vagrant up` command, I had two things to fill out.  The first was selecting which switch to connect to, and also the username and password for the SMB share:

image

I don't think that there is anything that can be done about either of those things.

**Comment by gep13** [comment]
I tried using `vagrant snapshot` which I "think" is meant to work, but I got an error

image

Pretty sure that this used to work the last time I tried it.  @mwrock is this something that you use?

**Comment by mwrock** [comment]
I'm fairly sure there is a way to specify the interface to use in the `vagrantfile` but not sure off the top of my head if you can specify the synced folder creds.

I've never used snapshots with vagrant so cant vouch for it with the hyper-v provider.

**Comment by gep13** [comment]
@mwrock I tried setting the vlan_id (https://www.vagrantup.com/docs/hyperv/configuration.html#vlan_id), thinking that this is what was required, but it seemed to ignore it.

It isn't the end of the world to have to provide those things, it just means the experience is slightly different.

Snapshotting would be a nice value add from the command line, but again, not the end of the world to have to jump to the Hyper-V manager, or directly call the CheckPoint-VM cmdlet.

**Comment by mwrock** [comment]
I think you can specify the switch using:

```
config.vm.network "public_network", bridge: "VirtualSwitchName"
```

**Comment by ferventcoder** [comment]
> During the vagrant up command, I had two things to fill out. The first was selecting which switch to connect to, and also the username and password for the SMB share

https://www.vagrantup.com/docs/hyperv/limitations.html#limited-networking

**Comment by gep13** [comment]
@ferventcoder thanks for pulling this in 👍

**Pull request merged**
